FROM alpine:3.16.2
LABEL maintainers="Alibaba Cloud Authors"
LABEL description="open-local is a local disk management system"
RUN apk update && apk upgrade && apk add util-linux coreutils xfsprogs e2fsprogs
COPY bin/open-local /bin/open-local
ENTRYPOINT ["open-local"]