kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.name }}-csi-snapshotter
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    component: {{ .Values.name }}-csi-snapshotter
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
      component: {{ .Values.name }}-csi-snapshotter
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        component: {{ .Values.name }}-csi-snapshotter
    spec:
      tolerations:
      - operator: Exists
        effect: NoSchedule
        key: node-role.kubernetes.io/master
      priorityClassName: system-cluster-critical
      serviceAccount: {{ .Values.name }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: csi-snapshotter
          image: {{ .Values.globalconfig.RegistryURL }}/{{ .Values.images.snapshotter.image }}:{{ .Values.images.snapshotter.tag }}
          args:
            - --csi-address=$(ADDRESS)
            - --snapshot-name-prefix=snap
            # no extra-create-metadata flag in v3.0.0
            # - --extra-create-metadata=true
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/plugins/{{ .Values.driver }}/csi.sock
            - name: TZ
              value: Asia/Shanghai
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 128Mi
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/kubelet/plugins/{{ .Values.driver }}
      volumes:
        - name: socket-dir
          hostPath:
            path: {{ .Values.agent.kubelet_dir }}/plugins/{{ .Values.driver }}
            type: DirectoryOrCreate
