apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-scheduler-extender
  namespace: {{ .Values.namespace }}
{{ include "local.labels" . | indent 2 }}
    app.kubernetes.io/component: {{ .Values.name }}-scheduler-extender
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ .Values.name }}-scheduler-extender
  template:
    metadata:
{{ include "local.labels" . | indent 6 }}
        app.kubernetes.io/component: {{ .Values.name }}-scheduler-extender
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      priorityClassName: system-cluster-critical
      tolerations:
      - operator: Exists
        effect: NoSchedule
        key: node-role.kubernetes.io/master
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Values.name }}-scheduler-extender
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - scheduler
        - --port={{ .Values.extender.port }}
        - --scheduler-strategy={{ .Values.extender.strategy }}
        image: {{ .Values.global.RegistryURL }}/{{ .Values.images.local.image }}:{{ .Values.images.local.tag }}
        imagePullPolicy: Always
        name: {{ .Values.name }}-scheduler-extender
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        env:
        - name: TZ
          value: Asia/Shanghai
      serviceAccount: {{ .Values.name }}
---
apiVersion: v1
kind: Service
metadata:
{{ include "local.labels" . | indent 2 }}
  name: {{ .Values.name }}-scheduler-extender
  namespace: {{ .Values.namespace }}
spec:
{{- if .Values.global.YodaSchedulerSvcIP }}
  clusterIP: {{ .Values.global.YodaSchedulerSvcIP }}
{{- end }}
  selector:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}-scheduler-extender
  ports:
  - protocol: TCP
    port: {{ .Values.extender.port }}
    targetPort: {{ .Values.extender.port }}
    name: http-port