apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  clusterIP: None
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
    name: http-metrics
  selector:
    app: minio
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: minio-external-service
  labels:
    app: minio
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
    name: http-metrics
  selector:
    app: minio
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: minio
  name: minio
spec:
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: minio
  serviceName: minio-service
  template:
    metadata:
      labels:
        app: minio
      name: minio
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
      - args:
        - server
        - /data
        env:
        - name: MINIO_PROMETHEUS_AUTH_TYPE
          value: public
        - name: MINIO_ROOT_USER
          value: minio
        - name: MINIO_ROOT_PASSWORD
          value: miniostorage
        image: minio/minio
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
            scheme: HTTP
        name: minio
        ports:
        - containerPort: 9000
          protocol: TCP
        volumeMounts:
        - mountPath: /data/
          name: minio-data
  volumeClaimTemplates:
  - metadata:
      name: minio-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: "10Gi"
      storageClassName: open-local-lvm-xfs
      volumeMode: Filesystem